COLOR_BAR  MACRO   COLOR, START_COL
			LOCAL   COL_LOOP, ROW_LOOP
			MOV     CX, START_COL + COLOR_MRGIN
			COL_LOOP:
				MOV     DX, COLOR_MRGIN
				ROW_LOOP:
					PAINT_PIXEL  COLOR
					INC     DX
					CMP     DX, COLOR_SIZE + COLOR_MRGIN
					JB      ROW_LOOP

					INC     CX
					CMP     CX, COLOR_SIZE + START_COL + COLOR_MRGIN
					JB      COL_LOOP
ENDM