FILL MACRO   COLOR, START_COL , START_ROW , END_COL , END_ROW
	          LOCAL       COL_LOOP, ROW_LOOP
	          MOV         CX, START_COL
	COL_LOOP: 
	          MOV         DX, START_ROW
	ROW_LOOP: 
	          PAINT_PIXEL COLOR
	          INC         DX
	          CMP         DX, END_ROW
	          JB          ROW_LOOP

	          INC         CX
	          CMP         CX, END_COL
	          JB          COL_LOOP
ENDM