SET_COLOR    MACRO
			LOCAL   SET_WHITE, SET_BLUE, SET_GREEN, SET_RED, END_CHOOSE
			CMP 	DX, COLOR_MRGIN + COLOR_SIZE
			JA 		END_CHOOSE
			CMP		DX, COLOR_MRGIN
			JB		END_CHOOSE
			CMP		CX, COLOR_MRGIN
			JB		END_CHOOSE
				CMP     CX, COLOR_MRGIN + WHITE_COL + COLOR_SIZE
				JB      SET_WHITE
				CMP     CX, RED_COL + COLOR_MRGIN + COLOR_SIZE
				JB      SET_RED
				CMP     CX, GREEN_COL + COLOR_MRGIN + COLOR_SIZE
				JB      SET_GREEN
				CMP     CX, BLUE_COL + COLOR_MRGIN + COLOR_SIZE
				JB      SET_BLUE
				JMP     END_CHOOSE
				
				SET_WHITE:
					MOV     PENCIL, WHITE
					JMP     END_CHOOSE
				SET_BLUE:
					MOV     PENCIL, BLUE
					JMP     END_CHOOSE
				SET_GREEN:
					MOV     PENCIL, GREEN
					JMP     END_CHOOSE
				SET_RED:
					MOV     PENCIL, RED
			END_CHOOSE:
ENDM